### ISSUE TITLE
When I restart VSCode I lost git

### ISSUE THREAD

**Issue by purocean** [andy-5/wslgit#1]
![image](https://user-images.githubusercontent.com/7115690/28725229-73a98458-73ef-11e7-89fb-139676a884cc.png)

**Comment by andy-5** [comment]
Can you check if it works from a Windows `cmd` console, i.e. something like this:

```
cd C:\PATH\TO\SOME\GIT\REPOSITORY
Y:\wslgit.exe rev-parse --show-toplevel
```

This should print the Windows path to the root directory of your git repository. For the previous example, it should print

```
C:/PATH/TO/SOME/GIT/REPOSITORY
```

**Comment by purocean** [comment]
Hang up forever

![image](https://user-images.githubusercontent.com/7115690/28807419-0a03e0fa-76a8-11e7-9c2d-3922fae96264.png)

**Comment by andy-5** [comment]
What happens if you execute `bash.exe` directly, because that is all `wslgit` does:

```
cd C:\PATH\TO\SOME\GIT\REPOSITORY
bash.exe -i -c "git rev-parse --show-toplevel"
```

This should print the Linux path to the git repository, i.e. something like `/mnt/c/PATH/TO/SOME/GIT/REPOSITORY`.

If that command also hangs, you can try to run bash without the `-i` flag like this:

```
bash.exe -c "git rev-parse --show-toplevel"
```

**Comment by purocean** [comment]
![image](https://user-images.githubusercontent.com/7115690/28814061-9aa7ab34-76ce-11e7-8c71-4f880fb3be87.png)

I use Fish shell，Is the why hangs?

**Comment by andy-5** [comment]
Yes, that seems to be the case. In interactive mode (with the `-i` flag), it looks like your shell does not execute the provided command. However, it works fine in non-interactive mode (without `-i`).

Currently, the `-i` flag is used by `wslgit` to ensure that things defined in `.bashrc`, like SSH agents, are executed before running any git commands. So I'd like to keep this flag.

I have no experience with the fish shell, but do you maybe start the fish shell from `.bashrc`, e.g. with `exec fish`? That would explain why it works in non-interactive mode.
If that is the case, maybe you just need to pass all arguments when starting the fish shell, like `exec fish "$@"`. Also, you propably would need to remove the greeting message of the fish shell, as this additional output prevents VSCode from correctly parsing the git output.

**Comment by purocean** [comment]
Thanks!

Use blow code to replace **exec fish**, resolved!

```bash
case $- in
    *c*) ;;
      *) exec fish;;
esac
```

**Comment by andy-5** [comment]
Great!
