### ISSUE TITLE
VSCode 1.19 and git repository constantly reopening

### ISSUE THREAD

**Issue by greggzst** [andy-5/wslgit#11]
The issue is that when I either open or close a file or even change a file tab I'm currently working on my git repository is reopened.

![Image](https://image.ibb.co/kizDzm/Capture.png)

Here I changed only two files but it says I've got 6 changes:

![Image](https://thumb.ibb.co/cNNBkR/Capture.png)

**Comment by andy-5** [comment]
I just uploaded a [new release](https://github.com/andy-5/wslgit/releases/tag/v0.4.0) that should fix this (based on changes from the fork https://github.com/purocean/wslproxy).
