### ISSUE TITLE
Install script 'mklink' command parameters should be quoted

### ISSUE THREAD

**Issue by rfgamaral** [andy-5/wslgit#110]
It seems the `mklink` calls should have the parameteres quoted, otherwise one gets this:

```
Make sure Fork.RI is executable in WSL...
OK.

Create 'git.exe' symlink...
The syntax of the command is incorrect.
OK.
```

Simply changing all `mklink` calls from this:
```
mklink %CMDDIR%\git.exe %CMDDIR%\wslgit.exe
```

To this:
```
mklink "%CMDDIR%\git.exe" "%CMDDIR%\wslgit.exe"
```

Seems to fix the issue.

I apologize for not being able to open a PR for this and speed up the process, sorry :(

**Comment by andy-5** [comment]
Thank you for reporting the issue, and describing the solution. I've uploaded a new release with the fixed install script.
