### ISSUE TITLE
Add `ssh-keygen.exe` or other tools

### ISSUE THREAD

**Issue by baxyz** [andy-5/wslgit#118]
I know that I'm going to ask a very specific thing, however, it could help other person in some way.

My motivation is to install Sailfish OS dev tools on Windows and trying to use WSL as much as possible.  
The installer expects **Git for Windows** and it checks if `ssh-keygen.exe` is aside the `bash.exe`.  
Of course, it fails because I use the `bash.exe` provided by `wslgit` and there is only `git.exe` available.

My request is: it's a wonderful idea to proxy `git.exe` to WSL git, can we go further by providing some useful tools? Maybe those about SSH keys, diffs, ...  
I do not say that it is smart to wrap all the 270 apps provided by **Git for Windows**, juste a few of them.

**Comment by andy-5** [comment]
I understand your request, but I think it is not in scope for this project to add other executables that are forwarded to WSL (the `bash.exe` is only a link to `wsl.exe`).

There are, however, quite a few projects that aim to forward arbitrary commands to WSL, e.g.:

- https://github.com/leongrdic/wsl-alias
- https://github.com/watzon/wsl-proxy
- https://github.com/jswh/wslexe
- https://github.com/Archenoth/wsl_proxy

I don't know how well they work, but maybe you can just add `ssh-keygen.exe` using one of these projects.

Please report back to this issue if you get it working, this might also be interesting for other users.
