### ISSUE TITLE
Version 1.1.0 does not work

### ISSUE THREAD

**Issue by leonheess** [andy-5/wslgit#122]
Installed it with Debian WSL1 on 10.0.18363 Build 18363 and added to PATH. git.exe from /cmd/ is used but the command is not relayed to WSL.

**Comment by andy-5** [comment]
Thank you for reporting this issue. I've confirmed that it does not work with Debian (but does work with Ubuntu). The reasion is the latest change to use the full path to `bash`, which was hardcoded to `/usr/bin/bash` - but this executable does not exist on Debian (where Bash is `/bin/bash`).

Until this is fixed, you can use the previous wslgit release.

**Comment by carlolars** [comment]
I did `which bash` on my Ubuntu installation and just took that path, but `/bin/bash` is the correct location (see [bash FILES](https://man7.org/linux/man-pages/man1/bash.1.html#FILES)).

Sorry for that mistake :/

**Comment by andy-5** [comment]
@carlolars I've pushed 5e343709d1149057a37103bd916c9cc535ec8bc8 to develop to change it to `/bin/bash` - does this still work for your original use case where the full path is required?

**Comment by andy-5** [comment]
Just released wslgit v1.1.1 which fixes this.
