### ISSUE TITLE
Error: 0x80070057

### ISSUE THREAD

**Issue by halaei** [andy-5/wslgit#13]
I have this error when running wslgit.exe:

Looking for git in: c:\src\wslgit.exe
Using git Error:  0 x 8 0 0 7 0 0 5 7

what's the problem?

**Comment by andy-5** [comment]
I have never seen an error like this.

Does it work from the command line, i.e. if you run
```
c:\src\wslgit.exe --version
```
from a `cmd` shell?

**Comment by andy-5** [comment]
This looks similar to bugs reported for WSL, e.g.:
https://github.com/Microsoft/WSL/issues/7
https://github.com/Microsoft/WSL/issues/2062

See the first one for a possible solution. It seems to occur only with certain consoles/environments.

As this is likely not related to `wslgit`, I'm closing this issue. Feel free to reply or open a new issue if you still have problems.
