### ISSUE TITLE
Source Tree

### ISSUE THREAD

**Issue by poniatowski** [andy-5/wslgit#136]
Hi! 

Does that program work with Source Tree as well? If so, where can I find the manual on how to set it with Source Tree/Windows 11/WSL2?

Thanks!

**Comment by GuyPaddock** [comment]
There is an open issue about this already. See https://github.com/andy-5/wslgit/issues/61.

**Comment by andy-5** [comment]
Closing as duplicate of #61, where there is already a lot of information.
