### ISSUE TITLE
GPG stuck

### ISSUE THREAD

**Issue by simonsmh** [andy-5/wslgit#14]
If I use GPG to sign my commit, the wslgit will stuck (instead of GPG password request) and the process will not go on.

**Comment by andy-5** [comment]
Do you run it within VS Code or from the command line?

From within VS Code, there is no way to interact with the processes executed in WSL, so you cannot enter a password.

If you run `wslgit` from the command line, it should be possible to input text. I haven't tried it with GPG to sign commits, but e.g. reading the commit message from stdin works.

**Comment by simonsmh** [comment]
That‘s right. Thank you.
