### ISSUE TITLE
When using wslgit.exe, vscode 1.19.1 shows 2 .git SCP

### ISSUE THREAD

**Issue by depadiernos** [andy-5/wslgit#15]
When using wslgit.exe, vscode 1.19.1 shows two `.git` source control providers. One is the working one (has the name of the repo) and the other is a non-working duplicate.

![image](https://user-images.githubusercontent.com/9113313/34644639-c3560a28-f2ff-11e7-82b4-645cc6735a4d.png)

**Comment by andy-5** [comment]
I just released a [new version](https://github.com/andy-5/wslgit/releases/tag/v0.5.0) which hopefully fixes this. Can you please test with the latest release?

**Comment by depadiernos** [comment]
I will as soon as possible. I'm not able to boot into Windows at the moment.

**Comment by andy-5** [comment]
I'm closing this, as it should already be fixed and there was no further feedback. Thanks for reporting.

**Comment by depadiernos** [comment]
Sorry for not getting around to testing. I appreciate the work you've put in. Thanks!
