### ISSUE TITLE
More information about "Usage from the command line"

### ISSUE THREAD

**Issue by donaldpipowitch** [andy-5/wslgit#22]
Hi,

I'm fairly new to Windows and PowerShell (that's one of the reasons I'd like to use WSL) and I struggle with this part:

> Just put the executable somewhere on your PATH and optionally rename it to git.exe. You can then just run any git command from a Windows console by running wslgit COMMAND or git COMMAND and it uses the Git version installed in WSL.

I followed this [guide to set my user/system environment variable](https://msdn.microsoft.com/de-de/library/windows/desktop/bb776899(v=vs.85).aspx) to configure `Path`. It now contains `C:\Users\me\git`. (I also tried `C:\Users\me\git.exe`.) But it doesn't seem to work. Any idea why? Thank you.

**Comment by andy-5** [comment]
You only need to add the directory containing the executable to the `Path` environment variable (not the executable itself), so in your case that would be `C:\Users\me`.

Also, you need to restart your shell for the changes to the environment variables to take effect.

I'm closing this, since this is not an issue with wslgit itself. Feel free to report back if it works, or ask additional questions if not.

**Comment by donaldpipowitch** [comment]
Thank! It does seem to work now in the PowerShell. It doesn't seem to work (yet) with [GitLens](https://github.com/eamodio/vscode-gitlens) and [SourceTree](https://www.sourcetreeapp.com/). Looking forward to further compability. Thank you for the work.

**Comment by andy-5** [comment]
Great!

I haven't tried it, but it seems GitLens uses its own configuration to set the Git executable, see 
[here](https://github.com/eamodio/vscode-gitlens#advanced-settings), in particular `gitlens.advanced.git`.

I don't know if you can specify the Git executable for SourceTree.

**Comment by donaldpipowitch** [comment]
Yeah, I tried both ways: Setting the explicit path in GitLens and SourceTree as well as using the `git.exe` in the `Path` environment. But maybe it doesn't work, because I'm not on an Insiders build. I haven't gotten any error messages (neither from GitLens nor SourceTree) it just seemed to load forever. :)

**Comment by andy-5** [comment]
Ah, yes, might be related to #9 (which is a Bug in WSL, currently only fixed in Insider builds).
