### ISSUE TITLE
"index out of bounds" when calling wslgit without arguments

### ISSUE THREAD

**Issue by pe224** [andy-5/wslgit#26]
I sucessfully built the latest version from source (on win).
Simply calling `wslgit.exe` (no arguments) fails with `thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1'`

Reason is [line 97](https://github.com/andy-5/wslgit/blob/4a61427123ec056fadb0c57d59bcb6862d13968e/src/main.rs#L97) as far as I can tell (not a Rust expert), as git_args[1] is out of bounds when wslgit is called with no arguments.

**Comment by andy-5** [comment]
Thanks for reporting! Yes, this line assumes at least one argument to git.

I'll fix it for the next version.
