### ISSUE TITLE
wslgit prints out additional newline character for single-line git outputs

### ISSUE THREAD

**Issue by pe224** [andy-5/wslgit#27]
I noticed this as VSCode gives an error when staging only selected changes.
For this, VSCode calls `git hash-object` and continues to use the output of this command.

Natively, `git hash-object` yields a single string, e.g. `"b7a2640fdd1d5ead24cc6340275b849e801bf6fe"` (no ending newline).

However, the output of `wslgit hash-object` for the same file will be `"b7a2640fdd1d5ead24cc6340275b849e801bf6fe\n"` (with ending newline).

This then leads to the error in VSCode.

Reason is [line 98-100](https://github.com/andy-5/wslgit/blob/4a61427123ec056fadb0c57d59bcb6862d13968e/src/main.rs#L98-L100) where the git output is split into lines, translated, and then printed out (via `println`).
If the original git output is only a single line without newline character, wslgit will still add a newline character due to `println`

As a Rust noob, I quick-fixed it with
```
let output_list: Vec<String> = output_str.lines().map(translate_path_to_win).collect();
print!("{}", output_list.join("\n"));
```

**Comment by pe224** [comment]
You are absolutely right. I'm sorry I was so quick in blaming wslgit.
It might actually be a bug in the VSCode git extension :)

If I click the gutter icon in a changed line a "peeking" window appears visualizing the diff.
If I then click on the + top right to only stage this particular change, git fails since it executes
```
git update-index --cacheinfo <mode> <object> <path>
```
where `<object>` = output of `git hash-object` **with** newline, which terminates the command early.

I don't have git for windows installed to test a "native combination" of git and VSCode, but I will try at home with a Linux box.
If the error appears there as well, the bug is probably in VSCode.

**Comment by pe224** [comment]
Have you tried it?
Something *is* different with wslgit after all, I just don't know what it is :)

On VSCode (Linux) with git (Linux) the partial staging indeed prints out a new line character after the hash into the `git update-index` command, but it works nonetheless. The newline character does not seem to terminate the command.

However, using VSCode (Win) and wslgit (Win) the newline character prematurely terminates the command and causes the error.
As you state correctly, the output (e.g. via python subprocess) is exactly the same in both cases. I have no idea why it generates a different behavior in VSCode. Maybe it has to do with OS-specific line endings \n vs \r\n?

**Comment by andy-5** [comment]
Thanks for this great test case. I also got the same result.

Thinking about it, I guess the `\n` is somewhere not correctly escaped when wslgit calls git via bash inside WSL, therefore terminating the command. I'll look into it.

**Comment by raleksandar** [comment]
It seems that this issue still persists, VSCode's Stage Selected Ranges command fails with:
```
> git update-index --cacheinfo 100644 69fc4cf61ef2280208f64b085f7b787a18747446
 path/to/file.ext
error: option 'cacheinfo' expects <mode>,<sha1>,<path>
```
A new line is being inserted between sha1 and path parameters.

**Comment by andy-5** [comment]
@raleksandar Yes, you are right. It works correctly when wslgit uses an interactive shell, but it does not work if `WSLGIT_USE_INTERACTIVE_SHELL` is set to `0` or `false`.

So this is only partially solved, and I need to look into the alternative execution path.

**Comment by phifa** [comment]
I just ran into the same issue. Let me know if I can help.

**Comment by andy-5** [comment]
With the latest changes from #76 it should now work for both interactive and non-interactive configurations. You can download an alpha build with these changes here: https://ci.appveyor.com/project/andy-5/wslgit/build/artifacts .
