### ISSUE TITLE
Using it in PHPStorm

### ISSUE THREAD

**Issue by amenk** [andy-5/wslgit#3]
Did anybody try wslgit in PHPStorm? We have problems :-) Is there a reason why it should not work?

**Comment by andy-5** [comment]
I have not tried it myself, but I also don't know why it shouldn't work.
Is there a git-console or something similar in PHPStorm, where you can see which commands are executed? That would be useful to reproduce why it doesn't work.

**Comment by amenk** [comment]
Usually yes but in this case nothing is logged, that is the strange thing.

**Comment by chris-imi** [comment]
I am working  with @amenk on this.
Now we get this error:

15:00:03.203: [intranet] git -c core.quotepath=false -c log.showSignature=false checkout -b develop origin/develop --
CreateProcess failed with error 2: Das System kann die angegebene Datei nicht finden.

(System can not find the specified file)

When we call git.exe directly via the cmd shell it is working, but not from PHPstorm

**Comment by andy-5** [comment]
Just a guess, but are you using a 64bit version of PHPStorm, or is it 32bit?

There could be a problem that 32bit applications cannot see the 64bit `bash.exe` as described here: https://superuser.com/a/1219130

**Comment by amenk** [comment]
Thanks for the hint. IS the problem just that we put wslgit.exe in system32\ ? I assume wslgit.exe is a 64bit app ?

**Comment by andy-5** [comment]
Maybe, have you tried putting it somewhere else?

Yes, `wslgit.exe` itself is a 64bit application.

**Comment by ccclausen** [comment]
Basically working, but we have other issues now (hanging git process) - opening an other ticket for that.
