### ISSUE TITLE
F-Secure AV complains

### ISSUE THREAD

**Issue by theel0ja** [andy-5/wslgit#35]
![image](https://user-images.githubusercontent.com/5832930/42380688-71ced81c-8137-11e8-9b36-4eae8bf8d31c.png)

https://www.f-secure.com/v-descs/w32_malware.shtml

**Comment by andy-5** [comment]
Thanks for the report.

There was already a similar false positive report from Avast in #7 . I'll try to get the `wslgit` binary on their whitelist to fix this.

**Comment by andy-5** [comment]
FYI, I got the following response from F-Secure:

> Our analysis indicate that the file you submitted is clean.
> 
> Our security product recently had a False Positive related to this file and the issue was fixed in a later database update. 

So this should be fixed with a database update of your F-Secure software. Can you verify that this is indeed the case?

**Comment by theel0ja** [comment]
F-secure won't block it anymore (unwhitelisted it first), but now SmartScreen is trying...

![image](https://user-images.githubusercontent.com/5832930/42480284-48babc06-83e5-11e8-9757-62e9be742511.png)
