### ISSUE TITLE
Flagged as "unsafe" by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by rfgamaral** [andy-5/wslgit#36]
Hi there,

My work laptop has Symantec Endpoint Protection installed, it's part of internal security policies, I cannot uninstall it. Unforunately it's flagging `wslgit.exe` as "unsafe" every time I use it. I tried to add an exception but it's not working, it popups the following every time:

![image](https://user-images.githubusercontent.com/96476/42687611-3d2d7636-8691-11e8-8cf5-54c2bcb5a5e9.png)

Is there anything that can be done on your side to prevent this from happening?

**Comment by andy-5** [comment]
Similar false positives were reported in #7 and #35 . They were resolved by filing false positive reports for the respective software (including a link to the Github issue).

I just reported wslgit as a false positive on Symantec's site, so hopefully this will be handled soon.

**Comment by andy-5** [comment]
I just got a response from Symantec that `wslgit.exe` will not be flagged anymore (after a database update within the next 24 hours).

Can you please confirm that it works now and that this issue can be closed?

**Comment by rfgamaral** [comment]
I don't think the database on my system is yet updated, give me a day or two and I'll report back, sounds good?

**Comment by rfgamaral** [comment]
@andy-5 It's no longer flagged, closing this. Thanks :)

**Comment by rfgamaral** [comment]
I'm having this issue again... :/

**Comment by andy-5** [comment]
Which binary is affected? The v0.8.0 release or the v0.9.0 alpha build?

**Comment by rfgamaral** [comment]
> 
> 
> Which binary is affected? The v0.8.0 release or the v0.9.0 alpha build?

All of them.

**Comment by rfgamaral** [comment]
I'm getting this again all the time:

![image](https://user-images.githubusercontent.com/96476/67794355-73f38400-fa74-11e9-9216-1272661204c1.png)

Isn't there a way to sign this file with some sort of Microsoft signature that would make Symantec ignore them or something?

**Comment by andy-5** [comment]
FYI, one can submit false positives at https://submit.symantec.com/false_positive/
I've now submitted the v0.8.0 release for checking.

I'm not sure if signing the executable would help. It may increase the reputation a little bit, but Symantec seems to report it because the file is very new and it hasn't seen it very often.

**Comment by rfgamaral** [comment]
> 
> 
> FYI, one can submit false positives at https://submit.symantec.com/false_positive/
> I've now submitted the v0.8.0 release for checking.

Good to know about this :)

However, v0.8.0 was not flagged for me, that one was fine. The problematic ones were the v0.9.0 alphas.

I've decided to compile my own binary and use that instead. Trying to see if it helps and avoids flagging by Symantec, we'll see how it goes.

**Comment by rfgamaral** [comment]
Closing this (again) since there's nothing else that can be done to improve this. Thanks @andy-5 .
