### ISSUE TITLE
Commit author and message are not working properly

### ISSUE THREAD

**Issue by benjaminprojas** [andy-5/wslgit#38]
I've just enabled wslgit.exe and it works great inside of Visual Studio Code with a couple issues:

![image](https://user-images.githubusercontent.com/962530/43920845-07ad8962-9be8-11e8-8da8-84005845fc5a.png)

As you can see there is no message and an incorrect author. Am I doing something incorrectly here?

**Comment by andy-5** [comment]
Regarding the author, you probably haven't setup Git inside WSL. As `wslgit` forwards all calls to the WSL version of Git, you need to configure it there, i.e. you need to run something like
```
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```
inside WSL to set the author name and email address.

Commit messages should work just fine, either using `-m "message"` on the command line, or entering a commit message in VS Code and committing with <kbd>Ctrl</kbd>+<kbd>Enter</kbd> . Otherwise, can you provide more information how you committed this revision (e.g. versions of VS Code, wslgit, WSL distro, VS Code extensions)?

**Comment by benjaminprojas** [comment]
@andy-5. Regarding the user name/email you were correct. Making that change fixed the issue. However the commit message still shows up as blank. I have been doing `Ctrl`+`Enter` as you mentioned. 

If I use the command line in my terminal (not inside VS Code) it works great. 

I am using wslgit release 0.6.0
I'm on VS Code 1.25.1 (latest).
Extensions: 
![image](https://user-images.githubusercontent.com/962530/44040354-089954a6-9ee9-11e8-9e71-9c0f365ae79b.png)

**Comment by andy-5** [comment]
Can you try disabling the GitLens extension? I remember someone reporting problems with GitLens in the past. Maybe it somehow affects the commit process.

You can also start VS Code with `code --disable-extensions` to temporary disable all extensions.

**Comment by benjaminprojas** [comment]
@andy-5 Okay I tried disabling just GitLens and that still didn't fix it, then I opened with no extensions like you mentioned and still no commit message... Any other ideas?

**Comment by andy-5** [comment]
Can you post the log from the Git output panel within VS Code? Maybe we can find something of interest there.

**Comment by benjaminprojas** [comment]
hey @andy-5 sorry for the delay in writing back.  This is what I see when I commit:

```
> git commit --quiet --allow-empty-message --file -
```

**Comment by andy-5** [comment]
Interesting, and now I can see you are using zsh. There have been some issues before with alternative shells. How did you setup zsh as your default shell? Do you start it from `.bashrc`?

In that case, you should only execute it if there is no command (using `-c`) passed to bash, as shown in https://github.com/andy-5/wslgit/issues/1#issuecomment-319322075 for the `fish` shell. Another possible solution is in https://github.com/andy-5/wslgit/issues/10#issuecomment-355671820 .

You could also try to set the Windows environment variable `WSLGIT_USE_INTERACTIVE_SHELL` to `false`, as explained in the [README](https://github.com/andy-5/wslgit#advanced-usage). This should prevent `.bashrc` from executing and therefore not invoke zsh (and it will also be faster).

**Comment by benjaminprojas** [comment]
@andy-5 Yep, that was it. I use `.bashrc` to instantiate zsh. I just added the line from https://github.com/andy-5/wslgit/issues/10#issuecomment-355671820 and it worked perfectly.  Thanks so much for taking the time to help me troubleshoot!
