### ISSUE TITLE
How to use GPG keys with passphrase?

### ISSUE THREAD

**Issue by Giraffe1966** [andy-5/wslgit#40]
I have some GPG keys for use with git, but they have passphrases. I can sign stuff as expected in WSL, but with wslgit.exe the passphrase prompt is unable to be displayed. How could I use GPG keys with passphrases with wslgit.exe?

**Comment by andy-5** [comment]
Some users reported in the past that they are successfully using GPG keys with `wslgit` (you can search the issues here), but I don't know wether they use passphrases or not.

If you use `gpg-agent`, it should be possible to cache the passphrase before you use `wslgit`, e.g. using `gpg-preset-passphrase`. This way, you need to enter it once in an interactive shell and the cached passphrase will then be reused for further commands, such as signing with `wslgit`.

Please let me know if you find a working solution.

I will keep this issue open for now, maybe someone else can share their GPG configuration.

**Comment by Giraffe1966** [comment]
I've got it working!
In WSL, add this to your ~/.gnupg/gpg.conf: `use-agent`
And this to your ~/.gnupg/gpg.conf to prevent cache expiry: `default-cache-ttl 34560000` and `max-cache-ttl 34560000`.
To cache a passphrase: `echo "test" | gpg2 -ase -r <keygrip> | gpg2` where <keygrip> is the keygrip of your key (Hint: gpg2 --with-keygrip --list-secret-keys).
Configure `git` in WSL to sign stuff by default.
Per repo: `git config commit.gpgSign true`
Global: `git config --global commit.gpgSign true`
Tell git which key to use:
Per repo: `git config user.signingKey <your_key_id>`
Global: `git config --global user.signingKey <your_key_id>`
And tell git to use gpg2: `git config --global gpg.program gpg2`

**Comment by andy-5** [comment]
Great! Thank your for sharing your solution!
