### ISSUE TITLE
1 more "not a git repository"

### ISSUE THREAD

**Issue by stasyaner** [andy-5/wslgit#45]
Hello. Can't get it working. Tried setting WSLGIT_USE_INTERACTIVE_SHELL to false/0 but nothing. It works fine from just CMD, but not from vscode. Could you please help? Thank you.

```
Looking for git in: D:\docs\wslgit.exe
Using git To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

git version 2.17.1 from D:\docs\wslgit.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: \To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

d:\docs\amedia
> git status -z -u
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by andy-5** [comment]
You seem to get the additional output
```
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

```
on every execution of wslgit. This prevents VS Code from correctly parsing the output of git.

I guess some bash startup file causes this. There is a discussion about this text on https://askubuntu.com/questions/22607 with a possible solution to remove it.

Does this fix it for you?

**Comment by stasyaner** [comment]
Oh, yeah. I should have guessed. Yeah, the resolution from that link helped. It's working fine now. Thank you a lot, @andy-5 !
