### ISSUE TITLE
fatal: bad revision '"--grep=Merge remote"' in Android studio

### ISSUE THREAD

**Issue by xhml** [andy-5/wslgit#55]
Android studio ：3.2.1

details:
```
Command line: [git -c core.quotepath=false -c log.showSignature=false log --pretty=format:%x01%x01%H%x02%x02%P%x02%x02%ct%x02%x02%an%x02%x02%ae%x02%x02%d%x03%x03 --encoding=UTF-8 --decorate=full HEAD --branches --remotes --tags "--grep=Merge remote" --fixed-strings --regexp-ignore-case --]
com.intellij.openapi.vcs.VcsException: fatal: bad revision '"--grep=Merge remote"'
```
![image](https://user-images.githubusercontent.com/14312777/46925995-72217300-d061-11e8-80b4-47433ac45027.png)

I set `WSLGIT_USE_INTERACTIVE_SHELL` to `0` in `User variables`  instead of `System variables`.

If there is other information to help you find the problem, please tell me how it should be provided.

**Comment by andy-5** [comment]
This looks very similar to #46, can you please check if the solution there fixes it for you?

**Comment by xhml** [comment]
Yes, my problem has been solved. Thank you and @diablodale.
