### ISSUE TITLE
WSLENV Environment Variable Flags Unsupported

### ISSUE THREAD

**Issue by sskeirik** [andy-5/wslgit#56]
According to https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/, when setting `WSLENV`, one can append each variable with flags that configure how the variable is shared. This includes the specifier `/u` which restricts the environment variable flow from Windows to WSL (which I think makes sense for this use case). Adding such a modifier causes the `WSLENV` variable check to fail.

Versions: tested on wslgit master on Windows 10 build 17134.345.

**Comment by andy-5** [comment]
Good find, thanks for reporting. Yes, the `WSLENV` check should allow for such modifiers.

**Comment by andy-5** [comment]
This should be fixed with the latest changes from #78. You can download an alpha build for testing here:
https://ci.appveyor.com/project/andy-5/wslgit/build/artifacts
