### ISSUE TITLE
Dumb question: I didn't get any exe after compiling?

### ISSUE THREAD

**Issue by ZYinMD** [andy-5/wslgit#57]
I didn't install Rust in Windows, I just downloaded Rust with WSL:
 `curl https://sh.rustup.rs -sSf | sh` - this was recommended on the official page. 
Is that why I didn't get any exe? Am I missing something?
![image](https://user-images.githubusercontent.com/32368482/48108125-dfaf6200-e20f-11e8-8ce0-d493a978db53.png)
![image](https://user-images.githubusercontent.com/32368482/48108194-29984800-e210-11e8-8cd9-153da8cd8160.png)

**Comment by andy-5** [comment]
Well, yes. You compiled wslgit using the Linux toolchain of Rust, and therefore get a Linux executable (the `wslgit` file in your screenshot).

But for wslgit to work, you need a Windows executable (a .exe), which AFAIK you can only compile with the Windows version of Rust.
