### ISSUE TITLE
wslgit not working on Windows 10 Version 1809

### ISSUE THREAD

**Issue by dsedmak** [andy-5/wslgit#59]
I was using wslgit without issue until I did a clean reinstall of the OS.  The new installation has the October/November update from Microsoft. The version is 1809 and the build is 17763.134.

VSCode displays the "No source control providers registered" and I cannot initialize a new repository.

However [https://gist.github.com/victor-perez/8ba25540394ec68b11f4b2699fb4d4ce](https://gist.github.com/victor-perez/8ba25540394ec68b11f4b2699fb4d4ce) worked so you might want to check if wslgit does things differently.

**Comment by andy-5** [comment]
I haven't yet tested it on 1809, but what exactly is not working? Can you run `wslgit.exe` from the command line? Does it show any errors?

If you have a clean install of the OS, you might be missing the [*Microsoft Visual C++ Redistributable for Visual Studio 2017*](https://aka.ms/vs/15/release/vc_redist.x64.exe).

**Comment by dsedmak** [comment]
Well now I feel dumb. Not having the redistributable installed was the problem.
Maybe you could make it so that you get an error in case you don't have the redistributable installed. RIght now invoking the exe via powershell outputs nothing and exits without any errors.
I'll leave the issue open in case you want to respond @andy-5 but the issue can be closed.

**Comment by andy-5** [comment]
Great that you got it working. Unfortunately, I can't show any errors because the executable does not even start without the missing libraries. I would have thought that there is some error message from Windows failing to load the executable, but that doesn't seem to be the case.
