### ISSUE TITLE
How should I merge the wslexe into wslgit

### ISSUE THREAD

**Issue by jswh** [andy-5/wslgit#63]
Hi!
Days ago I forked this project and did some changes to it.

First I changed the code to use file stem name as the command rather than `git` only.(python.exe for `python`, php.exe for `php`, etc)
Second , as different command may use different environment as interactive or not , I separated it into two binary files.
Third, more to the second reason, I made the command to source an environment script before executing the real command. This is useful for programs like python in virtualenv.

As the wslgit is only made for git, should I submit a PR to merge my code ?

my project:[ jswh/wslexe](https://github.com/jswh/wslexe)

**Comment by andy-5** [comment]
I have no plans to support any other tools besides git. So please do not file a PR, as I will not merge it. However, I guess it could be a useful tool for many, so you may want to continue working on it in your own repository.
