### ISSUE TITLE
Just add it to the PATH

### ISSUE THREAD

**Issue by spences10** [andy-5/wslgit#64]
>Just put the executable somewhere on your PATH and optionally rename it to git.exe. You can then just run any git command from a Windows console by running wslgit COMMAND or git COMMAND and it uses the Git version installed in WSL.

Please, saying just add it to the PATH doesn't help people that don't know how to just add to the PATH, can you be specific please as it's a bit ambiguous how to do this. 🙏

Add it to what path? The Windows one, the WSL one? It's not clear, if there was an example of how to add to the PATH then it would be very clear.

**Comment by andy-5** [comment]
Yes, exactly as described by @Coalpha.

I've changed the Readme to clarify this a bit. Thanks for the hint.
