### ISSUE TITLE
Include in WSL/VSC?

### ISSUE THREAD

**Issue by phifa** [andy-5/wslgit#66]
Thanks for building this tool. So good. 
But, should'nt this be natively implemented in VSC/WSL? Where could we submit this or upvote? 

I love WSL, and this this is the last missing piece, where we are still working with a workaround.

**Comment by andy-5** [comment]
Thanks, glad you find `wslgit` useful.

Other tools like VS Code would also need to implement some kind of bridge, similar to `wslgit`, to support WSL, but yes, ideally this would be natively integrated.

For VS Code specifically, you can follow/upvote this issue: https://github.com/Microsoft/vscode/issues/9502.

As this is not really an issue for `wslgit`, I'm closing this.
