### ISSUE TITLE
Commit message empty

### ISSUE THREAD

**Issue by phifa** [andy-5/wslgit#67]
![image](https://user-images.githubusercontent.com/3061129/54370734-72598500-4678-11e9-99bc-97cc37f74554.png)

My git log shows empty git messages when I commited code via VS Code. When I used wsl bash/zsh directly, the commit messages work.

**Comment by andy-5** [comment]
This looks similar to https://github.com/andy-5/wslgit/issues/38, please try one of the possible solutions posted in https://github.com/andy-5/wslgit/issues/38#issuecomment-416494102.

If that does not help:
- What versions of VS Code and wslgit are you using?
- Do you have the `WSLGIT_USE_INTERACTIVE_SHELL` environment variable set?
- And can you please provide the output of the Git log from within VS Code after you commited something (i.e. go to the `Output` tab and select `Git` from the dropdown on the right)

**Comment by phifa** [comment]
OK, got it working, I added `WSLGIT_USE_INTERACTIVE_SHELL false` to my windows user environmental variables. FYI I use zsh, that seemed to cause problems, as bash worked fine. Thanks

**Comment by andy-5** [comment]
Great!
