### ISSUE TITLE
Avast

### ISSUE THREAD

**Issue by Ayc0** [andy-5/wslgit#7]
Avast considers wslgit as a malware and deletes it

**Comment by andy-5** [comment]
I'm not sure I can do anything about that. I just reported it as a false positive at https://www.avast.com/false-positive-file-form.php, so hopefully a future update will fix that for you.

If you don't trust the binary releases, I suggest that you compile it yourself. Just install Rust from https://www.rust-lang.org (you will also need Visual Studio or the Visual C++ Build Tools) and build this project with `cargo build --release`. I've added instructions for compiling from source to the readme.

**Comment by andy-5** [comment]
FYI, I got an answer on my false positive report:

> Thank you for reporting this false positive.
> Our virus specialists have now cleared its reputation in our database.
> With URLs this change should be instant, but it might take up to 24 hours with files.

I hope this solved this issue for you (with the next definition update of your Avast installation). Closing this issue for now, feel free to re-open if the problem persists.
