### ISSUE TITLE
Translating to windows path from the root of a mounted drive does not work 

### ISSUE THREAD

**Issue by carlolars** [andy-5/wslgit#80]
`translate_path_to_win()` can not translate from the root of a mounted drive, for example the path `/mnt/d` does not translate to `d:`.

**Comment by carlolars** [comment]
> `translate_path_to_win()` can not translate from the root of a mounted drive, for example the path `/mnt/d` does not translate to `d:`.
It should actually translate to `d:/` for VSCode's git to work.

**Comment by andy-5** [comment]
Good catch, and thanks for your patch, which I just merged.
