### ISSUE TITLE
Access denied on ARM64

### ISSUE THREAD

**Issue by XiaoXice** [andy-5/wslgit#83]
I tried to cross-compile it with:
```
cargo build --release --target=aarch64-pc-windows-msvc
```
But when I try to run it, I get:
![image](https://user-images.githubusercontent.com/26328143/64507414-4a886880-d30d-11e9-8af7-84f0c69561e1.png)
The Chinese character "拒绝访问" means "Access denied" in English

**Comment by XiaoXice** [comment]
I tried again, and i find that it only works with a Administrator permission. If i open the vscode with admin permission, it can work normally. But for obvious reasons, i can't do it. Is there any workwround?

**Comment by andy-5** [comment]
Interesting, thank you for reporting this issue. I think you are the first one to try it on an ARM based device. Unfortunately, I've no idea why it would require Administrator permissions on ARM. 

Is the executable `wslgit.exe` owned by your normal user (maybe you compiled it in an Administrator console)?

Can you execute something like `wsl bash -c "git --version"` from the command line or from PowerShell as a normal user?

**Comment by XiaoXice** [comment]
Okey, I fixed it. Once you built it in the `git bash`, it will require admin permission. I rebuilt it in `cmd.exe`, and it works well on ARM64. Thanks very much!
