### ISSUE TITLE
Empty string argument is not passed to WSL

### ISSUE THREAD

**Issue by carlolars** [andy-5/wslgit#84]
One tool that I have configured to use `wslgit` tries to clear the _user.name_ using an empty string, like this:
```
C:\temp>wslgit config --global --replace-all user.name ""
error: wrong number of arguments, should be from 2 to 3
usage: git config [<options>]
...
```
It is not working since the empty string `""` is not even in the `env:args()` list, or at least I can not find it.  
I don't know if there are other times when empty string arguments are used, and I have no idea on how to fix this or if it even is possible.

**Comment by andy-5** [comment]
Interesting find, thanks for reporting. In a quick test, I was able to get empty strings out of `env::args()`, with e.g.:
```rust
    for argument in env::args() {
        println!("'{}'", argument);            
    }
```
But at that point, the quotes are not part of the string anymore. So the empty string seems to get lost somewhere, I guess at the latest here: https://github.com/andy-5/wslgit/blob/e7d971139295f2b3bffb81c8f8ededf301159df6/src/main.rs#L171

The simple solution is to just add quotes to empty strings.
