### ISSUE TITLE
Chocolatey installation

### ISSUE THREAD

**Issue by neilime** [andy-5/wslgit#85]
Hi,

Thank you for this usefull project.

Is there a chance to install wslgit via [Chocolatey](https://chocolatey.org) ?

Thank you

**Comment by andy-5** [comment]
That's a good idea, thank you for the suggestion.

Right now, I don't know how to get software into the Chocolatey package repository, maybe someone else can help here. Otherwise I'll look into it when I find some time.

**Comment by neilime** [comment]
@andy-5 I've created a request to chocolatey community to add your project in chocolatey packages: https://github.com/chocolatey-community/chocolatey-package-requests/issues/691

**Comment by neilime** [comment]
Et voilà : https://chocolatey.org/packages/WSLGit
