### ISSUE TITLE
WSLGIT=1 is not working for me

### ISSUE THREAD

**Issue by rfgamaral** [andy-5/wslgit#89]
This is my current `.bashrc` file:

```shell
echo '.bashrc'
echo "[${WSLGIT}]"
echo '.bashrc'

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

(...)
```

And I have this environment variables specified:

```
WINDOWS_USER=Ricardo
WSLENV=WINDOWS_USER/u
WSLGIT_MOUNT_ROOT=/
WSLGIT_USE_INTERACTIVE_SHELL=true
```

And here's what I get:

```
>wslgit --version
.bashrc
[]
.bashrc
git version 2.20.1
```

Am I doing something wrong?

**Comment by andy-5** [comment]
Just to make sure, are you using version 0.8.0 of `wslgit` or did you compile the current master branch?

The environment variable `WSLGIT` was only introduced after v0.8.0, and will be in the upcoming v0.9.0.
But the current readme shows the state of the master branch, which might be misleading, as these features are not in a release yet.

**Comment by rfgamaral** [comment]
I'm using v0.8.0, which I thought had that feature. I'll wait for v0.9.0 then. Any ETA?

**Comment by andy-5** [comment]
There is now [an alpha build available](https://ci.appveyor.com/project/andy-5/wslgit/build/artifacts) if you want to try it. If you do, please report back if it works as expected.

**Comment by rfgamaral** [comment]
> 
> 
> There is now [an alpha build available](https://ci.appveyor.com/project/andy-5/wslgit/build/artifacts) if you want to try it. If you do, please report back if it works as expected.

This worked, `WSLGIT` now was set as `1` with that version.

However, I got this from SmartGit:

![image](https://user-images.githubusercontent.com/96476/67626799-9608be80-f848-11e9-9e17-5b5ef63186d8.png)

Maybe I should post it in the other issue I've created about SmartGit compatibility...

**Comment by carlolars** [comment]
@andy-5 Maybe consider having a develop branch which is merged to master when you do a release? That would make the README less confusing since it would not contain any unreleased information.
